### ISSUE TITLE
Read conf variables from the environment

### ISSUE THREAD

**Issue by lrascao** [Kyorai/cuttlefish#16]
example conf:
```
param.p = $SOME_ENV_VARIABLE
```

cuttlefish would consult the environment for the SOME_ENV_VARIABLE key and replace it while processing the `.conf` file. I can put forward a PR for this, just wanted to first clear if this an appropriate syntax.

cc @lukebakken

**Comment by lrascao** [comment]
one other option is to use the current `$()` variable substitution and have it also search the environment.

**Comment by lukebakken** [comment]
My inclination is to use `$()`

**Comment by lukebakken** [comment]
Implemented in #17. Thank you!

**Comment by lrascao** [comment]
@lukebakken could you push `2.6.0` to hex please? thanks!

**Comment by lukebakken** [comment]
Please be patient! I was waiting on CI yesterday to complete when my day ended.

**Comment by lukebakken** [comment]
https://hex.pm/packages/cuttlefish/2.6.0

**Comment by lrascao** [comment]
thanks!
