### ISSUE TITLE
List datatype

### ISSUE THREAD

**Issue by lrascao** [Kyorai/cuttlefish#21]
I found a need for a `.conf` datatype parameter that is a list of something (string, integer, etc)

```

a = v1, v2, v3
```

I figured we could expand the list of [admissible datatypes](https://github.com/basho/cuttlefish/wiki/Datatypes) with a recursive `{list, Datatype}`
 format. Does this make sense? I already tried out the approach in a small branch with the minimal change.

**Comment by lrascao** [comment]
Early proposal at #22

**Comment by michaelklishin** [comment]
This idea sounds reasonable. Many projects currently use maps with ignored keys to accomplish this.

**Comment by lrascao** [comment]
closing via #22
