### ISSUE TITLE
Config for unix socket listeners

### ISSUE THREAD

**Issue by ioolkos** [Kyorai/cuttlefish#23]
I'd like to use Cuttlefish configuration for unix domain sockets similar to the following config snippet:
```
listener.tcp.default = 127.0.0.1:1883  ##normal listener
listener.tcp.unix_socket = local:/tmp/my.sock:0  ## uds listener
```
This will currently be captured and disallowed by the `ip` datatype validation here:
https://github.com/Kyorai/cuttlefish/blob/a0a3ed58da49e51fa980aa6901101900208d07df/src/cuttlefish_datatypes.erl#L302

Would an extension to that `ip` validation be the right approach? better ideas?

**Comment by michaelklishin** [comment]
Let's not extend the `ip` type and introduce a new one instead. `domain_socket` is what I'd use.

**Comment by ioolkos** [comment]
I understand. The thing is that this will lead to tons of duplicate boilerplate in your schema files (the domain socket will use TCP transport, can theoretically even use SSL). 

I think the best approach is to go just one step further and introduce a new datatype that corresponds to the Erlang `socket_address` so that it can match an IP address and a local address: `http://erlang.org/doc/man/inet.html#type-socket_address`
This will leave the existing `ip` type untouched.

**Comment by michaelklishin** [comment]
Sounds good.

**Comment by ioolkos** [comment]
I'll provide a PR. Will take a while as I need it to be part of a working end-to-end implementation.
Thanks!

**Comment by codeadict** [comment]
@ioolkos - Should we open a PR with your implementation on https://github.com/ioolkos/cuttlefish/tree/feature_domain_socket?

**Comment by ioolkos** [comment]
@codeadict Thanks, I forgot about this. It was just a quick hack but we can open a PR. In relation to Verne itself, there's still a minor issue: https://github.com/vernemq/vernemq/issues/2008
I think the  `ip_or_domain` data type messes up the initial default listener creation... maybe I haven't added a translation or sth similar.

**Comment by codeadict** [comment]
@ioolkos I think you can alsp have a single type, like domain_socket and specify 2 types in the schema like `[ip, domain_socket]` instead of having a composed type

**Comment by codeadict** [comment]
@ioolkos Added PR https://github.com/Kyorai/cuttlefish/pull/33 that fixes the VerneMQ issues we are facing with releases now
