### ISSUE TITLE
[Feature request] Provide a way to do character/string escaping

### ISSUE THREAD

**Issue by ChunyiLyu** [Kyorai/cuttlefish#37]
`#` is always treated as the start of a comment and there seems to be no way to do escaping in cuttlefish. This is a problem for the Cluster Operator and vault integration because passwords generated by vault could contain character `#` which leads to the value being read incorrectly by RabbitMQ (default user credentials are being configured via rabbitmq conf files in Cluster Op).

Could we consider adding character escaping into cuttlefish?

Related issue: https://github.com/rabbitmq/cluster-operator/issues/1326

**Comment by MaximPopov** [comment]
I second this request. There are other cases when `#` character is needed in a value, for example, MQTT topic match patterns.

Thanks!
