### ISSUE TITLE
[bug] Tag 2.0.1 conflicts with basho repo, obstructing synchronization

### ISSUE THREAD

**Issue by tburghart** [Kyorai/cuttlefish#54]
The `basho/cuttlefish` repo has tag `2.0.1` at commit `c92c8325aeaea6b6ba7516bbd434f8e408f87d60`, in appropriate chronological sequence between tags `2.0.0` and `2.0.2`.

The `Kyorai/cuttlefish` repo erroneously places tag `2.0.1` at commit `bd2660f6e090e88556baf203b2769b9319a780d5`, a full year out of chronological sequence between tags `2.0.5` and `2.0.6`.

At this point in time this tag should be irrelevant for all users, but it still causes automation problems for those of us who maintain composites derived from both (3).

It seems that it should be safe at this point for one of the Kyorai repo owners to:
* Delete the 2.0.1 tag from the Kyorai repo.
* Fetch tags (or just 2.0.1) from the basho repo (1).
* Push the fetched 2.0.1 tag to the Kyorai repo (2).

Notes:
1. It is important that the tag be fetched/pushed rather than recreated in order to eliminate the conflict.
2. There are differences in the tagging of versions `2.1.0 =/= v2.1.0` and `2.1.1 =/= v2.1.1` between the two repos but as these do not conflict on names _and_ are quite old they can safely be ignored.
3. The goal is to have the ErlEF OpenRiak project's cuttlefish repo seamlessly merge these two sources into a single consistently-versioned reference that can be subsequently kept up to date.

**Comment by michaelklishin** [comment]
@tburghart I will delete the problematic tag. Would that not suffice for your needs? I am not sure why we should still follow basho/cuttlefish, the whole idea of changing the org was to not depend on it.

But I also don't want to make things unnecessarily complicated for the maintainers of modern Riak.

**Comment by tburghart** [comment]
@michaelklishin Yes, that would be fine - anyone who fetches from both repos will get the full set of tags without conflicts, which is really all we care about.
Thanks!

**Comment by michaelklishin** [comment]
@tburghart I have [deleted the problematic tag](https://github.com/Kyorai/cuttlefish/tags?after=2.0.3).
